const express = require('express')
const app = express()
const port = process.env.PORT || 3000

// let products = {
//   1: {
//     id: '1',
//     description: 'Widget',
//   },
//   2: {
//     id: '2',
//     description: 'Thing',
//   },
// };
app.get('/products', (req, res) => {
  return res.send(products[Math.floor(Math.random()*products.length)]);
}); 

app.listen(port, () => {
  console.log(`App listening at http://localhost:${port}`)
})

// let products = [{"id":1,"description":"Star Anise, Whole"},
// {"id":2,"description":"Flower - Commercial Bronze"},
// {"id":3,"description":"Milk - Skim"},
// {"id":4,"description":"Lettuce - Treviso"},
// {"id":5,"description":"Pork - Loin, Center Cut"},
// {"id":6,"description":"Coffee Cup 8oz 5338cd"},
// {"id":7,"description":"Flour - Strong"},
// {"id":8,"description":"Gin - Gilbeys London, Dry"},
// {"id":9,"description":"Broccoli - Fresh"},
// {"id":10,"description":"Cod - Black Whole Fillet"},
// {"id":11,"description":"Soup - Campbells, Chix Gumbo"},
// {"id":12,"description":"Jam - Raspberry,jar"},
// {"id":13,"description":"Bread - Rye"},
// {"id":14,"description":"Scallops - In Shell"},
// {"id":15,"description":"Tea - Herbal - 6 Asst"},
// {"id":16,"description":"Bread - Roll, Calabrese"},
// {"id":17,"description":"Island Oasis - Pina Colada"},
// {"id":18,"description":"Artichokes - Knobless, White"},
// {"id":19,"description":"Nut - Pumpkin Seeds"},
// {"id":20,"description":"Asparagus - White, Fresh"},
// {"id":21,"description":"Silicone Parch. 16.3x24.3"},
// {"id":22,"description":"Coffee - Cafe Moreno"},
// {"id":23,"description":"Cafe Royale"},
// {"id":24,"description":"Wine - White Cab Sauv.on"},
// {"id":25,"description":"Beef - Top Sirloin"},
// {"id":26,"description":"Lettuce - Romaine, Heart"},
// {"id":27,"description":"Irish Cream - Butterscotch"},
// {"id":28,"description":"Clams - Canned"},
// {"id":29,"description":"Drambuie"},
// {"id":30,"description":"Wine - Red, Wolf Blass, Yellow"},
// {"id":31,"description":"Sole - Fillet"},
// {"id":32,"description":"Table Cloth 72x144 White"},
// {"id":33,"description":"Crackers - Graham"},
// {"id":34,"description":"Mousse - Mango"},
// {"id":35,"description":"Shrimp - 16/20, Iqf, Shell On"},
// {"id":36,"description":"Pastry - Key Limepoppy Seed Tea"},
// {"id":37,"description":"Rice Pilaf, Dry,package"},
// {"id":38,"description":"Vodka - Hot, Lnferno"},
// {"id":39,"description":"Longos - Chicken Curried"},
// {"id":40,"description":"Towel Multifold"},
// {"id":41,"description":"Sauce - Plum"},
// {"id":42,"description":"Soup - Campbells Broccoli"},
// {"id":43,"description":"Amaretto"},
// {"id":44,"description":"Pastry - Key Limepoppy Seed Tea"},
// {"id":45,"description":"Sauce - Sesame Thai Dressing"},
// {"id":46,"description":"Beef Striploin Aaa"},
// {"id":47,"description":"Turkey - Whole, Fresh"},
// {"id":48,"description":"Nantucket - 518ml"},
// {"id":49,"description":"Yogurt - Cherry, 175 Gr"},
// {"id":50,"description":"Beer - Corona"}];

let products = [
  {
    "ID": 17,
    "Type": "variable",
    "SKU": "MH01",
    "Name": "Chaz Kangeroo Hoodie",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "This is a variable product called a Chaz Kangeroo Hoodie",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 0,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": null,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XS|S|M|L|XL",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black|Gray|Orange",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 11,
    "Type": "variation",
    "SKU": "MH01-L-Black",
    "Name": "Chaz Kangeroo Hoodie-L-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-black_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "L",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 12,
    "Type": "variation",
    "SKU": "MH01-L-Gray",
    "Name": "Chaz Kangeroo Hoodie-L-Gray",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "L",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Gray",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 13,
    "Type": "variation",
    "SKU": "MH01-L-Orange",
    "Name": "Chaz Kangeroo Hoodie-L-Orange",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-orange_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "L",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Orange",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 8,
    "Type": "variation",
    "SKU": "MH01-M-Black",
    "Name": "Chaz Kangeroo Hoodie-M-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-black_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "M",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 9,
    "Type": "variation",
    "SKU": "MH01-M-Gray",
    "Name": "Chaz Kangeroo Hoodie-M-Gray",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "M",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Gray",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 10,
    "Type": "variation",
    "SKU": "MH01-M-Orange",
    "Name": "Chaz Kangeroo Hoodie-M-Orange",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-orange_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "M",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Orange",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 5,
    "Type": "variation",
    "SKU": "MH01-S-Black",
    "Name": "Chaz Kangeroo Hoodie-S-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-black_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "S",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 6,
    "Type": "variation",
    "SKU": "MH01-S-Gray",
    "Name": "Chaz Kangeroo Hoodie-S-Gray",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "S",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Gray",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 7,
    "Type": "variation",
    "SKU": "MH01-S-Orange",
    "Name": "Chaz Kangeroo Hoodie-S-Orange",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-orange_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "S",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Orange",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 14,
    "Type": "variation",
    "SKU": "MH01-XL-Black",
    "Name": "Chaz Kangeroo Hoodie-XL-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-black_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XL",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 15,
    "Type": "variation",
    "SKU": "MH01-XL-Gray",
    "Name": "Chaz Kangeroo Hoodie-XL-Gray",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XL",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Gray",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 16,
    "Type": "variation",
    "SKU": "MH01-XL-Orange",
    "Name": "Chaz Kangeroo Hoodie-XL-Orange",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-orange_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XL",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Orange",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 2,
    "Type": "variation",
    "SKU": "MH01-XS-Black",
    "Name": "Chaz Kangeroo Hoodie-XS-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-black_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XS",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 3,
    "Type": "variation",
    "SKU": "MH01-XS-Gray",
    "Name": "Chaz Kangeroo Hoodie-XS-Gray",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XS",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Gray",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 4,
    "Type": "variation",
    "SKU": "MH01-XS-Orange",
    "Name": "Chaz Kangeroo Hoodie-XS-Orange",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Ideal for cold-weather training or work outdoors, the Chaz Hoodie promises superior warmth with every wear. Thick material blocks out the wind as ribbed cuffs and bottom band seal in body heat.</p> <p>&bull; Two-tone gray heather hoodie.<br />&bull; Drawstring-adjustable hood. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 52,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh01-orange_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH01",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XS",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Orange",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 33,
    "Type": "variable",
    "SKU": "MH02",
    "Name": "Teton Pullover Hoodie",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "This is a variable product called a Teton Pullover Hoodie",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 0,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": null,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-black_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XS|S|M|L|XL",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black|Purple|Red",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 27,
    "Type": "variation",
    "SKU": "MH02-L-Black",
    "Name": "Teton Pullover Hoodie-L-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-black_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "L",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 28,
    "Type": "variation",
    "SKU": "MH02-L-Purple",
    "Name": "Teton Pullover Hoodie-L-Purple",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-purple_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "L",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Purple",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 29,
    "Type": "variation",
    "SKU": "MH02-L-Red",
    "Name": "Teton Pullover Hoodie-L-Red",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-red_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "L",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Red",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 24,
    "Type": "variation",
    "SKU": "MH02-M-Black",
    "Name": "Teton Pullover Hoodie-M-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-black_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "M",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 25,
    "Type": "variation",
    "SKU": "MH02-M-Purple",
    "Name": "Teton Pullover Hoodie-M-Purple",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-purple_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "M",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Purple",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 26,
    "Type": "variation",
    "SKU": "MH02-M-Red",
    "Name": "Teton Pullover Hoodie-M-Red",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-red_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "M",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Red",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 21,
    "Type": "variation",
    "SKU": "MH02-S-Black",
    "Name": "Teton Pullover Hoodie-S-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-black_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "S",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 22,
    "Type": "variation",
    "SKU": "MH02-S-Purple",
    "Name": "Teton Pullover Hoodie-S-Purple",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-purple_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "S",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Purple",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 23,
    "Type": "variation",
    "SKU": "MH02-S-Red",
    "Name": "Teton Pullover Hoodie-S-Red",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-red_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "S",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Red",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 30,
    "Type": "variation",
    "SKU": "MH02-XL-Black",
    "Name": "Teton Pullover Hoodie-XL-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-black_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XL",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 31,
    "Type": "variation",
    "SKU": "MH02-XL-Purple",
    "Name": "Teton Pullover Hoodie-XL-Purple",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-purple_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XL",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Purple",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 32,
    "Type": "variation",
    "SKU": "MH02-XL-Red",
    "Name": "Teton Pullover Hoodie-XL-Red",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-red_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XL",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Red",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 18,
    "Type": "variation",
    "SKU": "MH02-XS-Black",
    "Name": "Teton Pullover Hoodie-XS-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-black_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh02-black_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XS",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 19,
    "Type": "variation",
    "SKU": "MH02-XS-Purple",
    "Name": "Teton Pullover Hoodie-XS-Purple",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-purple_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XS",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Purple",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 20,
    "Type": "variation",
    "SKU": "MH02-XS-Red",
    "Name": "Teton Pullover Hoodie-XS-Red",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>This Teton Pullover Hoodie gives you more than laid-back style. It's equipped with moisture-wicking fabric to keep light and dry inside, especially in chilly-weather workouts. An elasticized hem lets you move about freely.</p> <p>&bull; Black pullover hoodie.<br />&bull; Soft, brushed interior. <br />&bull; Front hand pockets. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 70,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh02-red_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH02",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XS",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Red",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 49,
    "Type": "variable",
    "SKU": "MH03",
    "Name": "Bruno Compete Hoodie",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "This is a variable product called a Bruno Compete Hoodie",
    "description": "<p>Stay comfortable and stay in the race no matter what the weather's up to. The Bruno Compete Hoodie's water-repellent exterior shields you from the elements, while advanced fabric technology inside wicks moisture to keep you dry.</p> <p>&bull; Full zip black hoodie pullover. <br />&bull; Adjustable drawstring hood. <br />&bull; Ribbed cuffs/waistband. <br />&bull; Kangaroo pocket. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 0,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": null,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 63,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh03-black_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh03-black_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh03-black_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "XS|S|M|L|XL",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black|Blue|Green",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 43,
    "Type": "variation",
    "SKU": "MH03-L-Black",
    "Name": "Bruno Compete Hoodie-L-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Stay comfortable and stay in the race no matter what the weather's up to. The Bruno Compete Hoodie's water-repellent exterior shields you from the elements, while advanced fabric technology inside wicks moisture to keep you dry.</p> <p>&bull; Full zip black hoodie pullover. <br />&bull; Adjustable drawstring hood. <br />&bull; Ribbed cuffs/waistband. <br />&bull; Kangaroo pocket. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 63,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh03-black_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh03-black_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh03-black_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH03",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "L",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 44,
    "Type": "variation",
    "SKU": "MH03-L-Blue",
    "Name": "Bruno Compete Hoodie-L-Blue",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Stay comfortable and stay in the race no matter what the weather's up to. The Bruno Compete Hoodie's water-repellent exterior shields you from the elements, while advanced fabric technology inside wicks moisture to keep you dry.</p> <p>&bull; Full zip black hoodie pullover. <br />&bull; Adjustable drawstring hood. <br />&bull; Ribbed cuffs/waistband. <br />&bull; Kangaroo pocket. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 63,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh03-blue_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH03",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "L",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Blue",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 45,
    "Type": "variation",
    "SKU": "MH03-L-Green",
    "Name": "Bruno Compete Hoodie-L-Green",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Stay comfortable and stay in the race no matter what the weather's up to. The Bruno Compete Hoodie's water-repellent exterior shields you from the elements, while advanced fabric technology inside wicks moisture to keep you dry.</p> <p>&bull; Full zip black hoodie pullover. <br />&bull; Adjustable drawstring hood. <br />&bull; Ribbed cuffs/waistband. <br />&bull; Kangaroo pocket. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 63,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh03-green_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH03",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "L",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Green",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 40,
    "Type": "variation",
    "SKU": "MH03-M-Black",
    "Name": "Bruno Compete Hoodie-M-Black",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Stay comfortable and stay in the race no matter what the weather's up to. The Bruno Compete Hoodie's water-repellent exterior shields you from the elements, while advanced fabric technology inside wicks moisture to keep you dry.</p> <p>&bull; Full zip black hoodie pullover. <br />&bull; Adjustable drawstring hood. <br />&bull; Ribbed cuffs/waistband. <br />&bull; Kangaroo pocket. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 63,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh03-black_main.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh03-black_alt1.jpg,http://eimages.valtim.com/acme-images/product/m/h/mh03-black_back.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH03",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "M",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Black",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 41,
    "Type": "variation",
    "SKU": "MH03-M-Blue",
    "Name": "Bruno Compete Hoodie-M-Blue",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Stay comfortable and stay in the race no matter what the weather's up to. The Bruno Compete Hoodie's water-repellent exterior shields you from the elements, while advanced fabric technology inside wicks moisture to keep you dry.</p> <p>&bull; Full zip black hoodie pullover. <br />&bull; Adjustable drawstring hood. <br />&bull; Ribbed cuffs/waistband. <br />&bull; Kangaroo pocket. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 63,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh03-blue_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH03",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "M",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Blue",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  },
  {
    "ID": 42,
    "Type": "variation",
    "SKU": "MH03-M-Green",
    "Name": "Bruno Compete Hoodie-M-Green",
    "Published": 1,
    "Is featured?": 0,
    "Visibility in catalog": "visible",
    "Short description": "",
    "description": "<p>Stay comfortable and stay in the race no matter what the weather's up to. The Bruno Compete Hoodie's water-repellent exterior shields you from the elements, while advanced fabric technology inside wicks moisture to keep you dry.</p> <p>&bull; Full zip black hoodie pullover. <br />&bull; Adjustable drawstring hood. <br />&bull; Ribbed cuffs/waistband. <br />&bull; Kangaroo pocket. <br />&bull; Machine wash/dry.</p>",
    "Date sale price starts": "",
    "Date sale price ends": "",
    "Tax status": "",
    "Tax class": "",
    "In stock?": 1,
    "Stock": 100,
    "Backorders allowed?": 0,
    "Sold individually?": 0,
    "Weight (lbs)": 1,
    "Length (in)": "",
    "Width (in)": "",
    "Height (in)": "",
    "Allow customer reviews?": 1,
    "Purchase note": "",
    "Sale price": null,
    "Regular price": 63,
    "Categories": "Clothing>Men>Tops>Hoodies & Sweatshirts|Clothing>Collections>Eco Friendly|Clothing",
    "Tags": "",
    "Shipping class": "",
    "Images": "http://eimages.valtim.com/acme-images/product/m/h/mh03-green_main.jpg",
    "Download limit": "",
    "Download expiry days": "",
    "Parent": "MH03",
    "Grouped products": "",
    "Upsells": "",
    "Cross-sells": "",
    "External URL": "",
    "Button text": "",
    "Position": "",
    "Attribute 1 name": "Size",
    "Attribute 1 value(s)": "M",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Green",
    "Attribute 3 name": "",
    "Attribute 3 value(s)": "",
    "Attribute 4 name": "",
    "Attribute 4 value(s)": "",
    "Attribute 5 name": "",
    "Attribute 5 value(s)": "",
    "Meta: _wpcom_is_markdown": "",
    "Download 1 name": "",
    "Download 1 URL": "",
    "Download 2 name": "",
    "Download 2 URL": ""
  }];
